---
- name: Enable other packages
  lineinfile:
    dest: /etc/apt/sources.list
    regexp: '^# deb-src'
    line: "deb-src http://raspbian.raspberrypi.org/raspbian/ stretch main contrib non-free rpi"
  become: True

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install required packages
  apt:
    name: "{{item}}"
    state: present
  become: True
  with_items:
    - htop
    - vim
    - git-core

- name: Install docker
  pip:
    name: docker
  become: True
